
"use client";

import { useEffect, useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load Google Fontss
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // State to track if the component is mounted on the client-side
  const [isClient, setIsClient] = useState(false);

  // Client-side effects
  useEffect(() => {
    setIsClient(true); // Indicate client-side rendering
  }, []);

  // If not on client, return a static layout (for SSR)
  if (!isClient) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} cz-shortcut-listen="true">
          {children}
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
         <head>
          {/* Add your google-site-verification meta tag here */}
          <meta name="google-site-verification" content="FMXhlg_sDLAk2KThGcEpIW7d-QM9gy6IVY8MmCa4I8I" />
          {/* You can add any other meta tags, links, or scripts here */}
        </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
